export const SIGNUP = 'SIGNUP';
export const SIGNUP_PASS_MSG = 'SIGNUP_PASS_MSG';
export const SIGNUP_FAIL_MSG = 'SIGNUP_FAIL_MSG';

export const LOGIN = 'LOGIN';
export const LOGIN_PASS_MSG = 'LOGIN_PASS_MSG';
export const LOGIN_FAIL_MSG = 'LOGIN_FAIL_MSG';

export const GET_ALL_MENU = 'GET_ALL_MENU';
export const GET_ALL_MENU_PASS_MSG = 'GET_ALL_MENU_PASS_MSG';
export const GET_ALL_MENU_FAIL_MSG = 'GET_ALL_MENU_FAIL_MSG';

export const POST_ORDER = 'POST_ORDER';
export const POST_ORDER_PASS_MSG = 'POST_ORDER_PASS_MSG';
export const POST_ORDER_FAIL_MSG = 'POST_ORDER_FAIL_MSG';

export const GET_ORDERS = 'GET_ORDER';
export const GET_ORDERS_PASS_MSG = 'GET_ORDER_PASS_MSG';
export const GET_ORDERS_FAIL_MSG = 'GET_ORDER_FAIL_MSG';
